# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do | chef |
    chef.cookbooks_path = "site-cookbooks"
    chef.add_recipe "mongodb::10gen_repo"
    chef.add_recipe "memcached"
    chef.add_recipe "python"
    chef.add_recipe "mongodb::default"
    chef.add_recipe "rabbitmq"
  end

end
