language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libgeos-c1 libprotobuf-dev protobuf-compiler
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "curl -o JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - python setup.py test
  - java -jar JsTestDriver-1.3.3d.jar --reset --port 9874 --browser firefox --tests all --config JSTestDriver.jstd
notifications:
  irc:
    channels:
      - "irc.freenode.org#molly"
    on_success: change