language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libgeos-c1 libprotobuf-dev protobuf-compiler
install:
  - python setup.py develop
script:
  - python setup.py test